# Usage
# rpmbuild --undefine=_disable_source_fetch -ba pam_ssh_agent.spec

# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

%if 0%{?fedora} <= 43
# define versions of built-in dependencies
%define         pam_bindings	        0.1.1
%define         ssh_agent_client_rs     0.9.1
%endif

Name:           pam_ssh_agent
Version:        0.5.1
Release:        1
Summary:        PAM module for ssh-agent based authentication

SourceLicense:  MIT
License:        Apache-2.0 or MIT

URL:            https://github.com/nresare/pam-ssh-agent
Source0:        https://github.com/nresare/pam-ssh-agent/archive/v%{version}/%{name}-%{version}.tar.gz


# built-in dependencies
%if "%{pam_binding}" != ""
%define         has_bundles 1
Source10:       https://static.crates.io/crates/pam-bindings/pam-bindings-%{pam_bindings}.crate
Provides:       bundled(crate(pam-binding)) = %{pam_bindings}
%else
BuildRequires:  rust-pam-bindings+default-devel
%endif

%if "%{ssh_agent_client_rs}" != ""
%define         has_bundles 1
Source11:       https://static.crates.io/crates/ssh-agent-client-rs/ssh-agent-client-rs-%{ssh_agent_client_rs}.crate
Provides:       bundled(crate(ssh-agent-client-rs)) = %{ssh_agent_client_rs}
BuildRequires:  rust-bytes-devel
BuildRequires:  rust-thiserror1-devel
%else
BuildRequires:  rust-ssh-agent-client-rs+default-devel
%endif

BuildRequires:  cargo-rpm-macros >= 26

## from Cargo.toml
BuildRequires:  rust-anyhow+default-devel
BuildRequires:  rust-getrandom0.2+default-devel	
BuildRequires:  rust-signature+default-devel
BuildRequires:  rust-ssh-key+crypto-devel
BuildRequires:  rust-ssh-key+default-devel
BuildRequires:  rust-syslog+default-devel


%global _description %{expand:
%{summary}.}

%description %{_description}


%prep
%autosetup -n pam-ssh-agent-%{version} -p1

# built-in dependencies
%if "%{pam_binding}" != ""
%{__tar} xzf %{SOURCE10}
%{__sed} -i 's/pam-bindings = .*/pam-bindings = { path = "pam-bindings-%{pam_bindings}" }/' Cargo.toml
%endif

%if "%{ssh_agent_client_rs}" != ""
%{__tar} xzf %{SOURCE11}
%{__sed} -i 's/ssh-agent-client-rs = .*/ssh-agent-client-rs = { path = "ssh-agent-client-rs-%{ssh_agent_client_rs}" }/' Cargo.toml
%endif

%cargo_prep


%generate_buildrequires
%if 0%{has_bundles}
%else
%cargo_generate_buildrequires
%endif


%build
%cargo_build
%{cargo_license_summary}


%install
install -d -m 755 %{buildroot}%{_libdir}/security
install -m 755 target/release/libpam_ssh_agent.so %{buildroot}%{_libdir}/security


%check
%if %{with check}
%cargo_test
%endif


%files
%doc README.md
%{_libdir}/security/libpam_ssh_agent.so


%changelog
* Mon May 12 2025 Peter Bieringer <pb@bieringer.de> - 0.5.1-1
- Upstream 0.5.1 incl. bundled pam-bindings=0.1.1 and ssh-agent-client-rs=0.9.1
